name: Build Dev APK

on:
  push:
    branches:
      - dev_lavan8t

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Give Gradle permission
        run: chmod +x gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.1-dev
          name: 1.1 dev
          prerelease: true
          files: app/build/outputs/apk/debug/app-debug.apk
